MACHINES = {
	:"kernel-update" => {
		:box_name => "ubuntu/23.10",
		:cpus => 2,
		:memory => 1024,
		}
}

Vagrant.configure("2") do |config|
	MACHINES.each do |boxname, boxconfig|
		config.vm.synced_folder ".", "/vagrant", disabled: true
		config.vm.define boxname do |box|
			box.vm.box = boxconfig[:box_name]
			box.vm.host_name = boxname.to_s
			box.vm.provider "virtualbox" do |v|
				v.cpus = boxconfig[:cpus]
				v.memory = boxconfig[:memory]
			end
		end
	end
#config.vm.box = "ubuntu/23.04"
end
